# Steps to add new samples
1. Run entire pipeline and save images in `v1/`
2. Manually go through images and write down the name (`uuid`) of the images that are not suitable.
3. Remove this images and save the resulting ones in `v2/`
4. Launch this notebook to download missing samples. Repeat as needed

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
df_clustered = pd.read_csv("download_imgs/clustered_points.csv")
df_clustered

/var/folders/kw/9lnn_1r159n28p1krywmf8_w0000gq/T/ipykernel_64200/2871462531.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_clustered = pd.read_csv("download_imgs/clustered_points.csv")

,Unnamed: 0,Unnamed: 0_x,uuid_x,source,orig_id,city,city_ascii,city_id,city_lat,city_lon,...,Car-Mount,Ego-Vehicle,Total,visual_complexity,Road_ratio,Vegetation_ratio,Car_ratio,Building_ratio,Sky_ratio,cluster_label
0,0,37185,1c80da17-697e-485b-b513-7925b07d8d92,Mapillary,865783177614020,Singapore,Singapore,1702341327,1.30,103.8000,...,0.0,0.0,2044260.0,1.876654,0.118965,0.060797,0.016989,0.136482,0.278301,2
1,1,37221,e256fdf0-c55f-48fc-b55c-13b310243e3b,Mapillary,826518501302716,Singapore,Singapore,1702341327,1.30,103.8000,...,0.0,107425.0,2005395.0,1.993278,0.079747,0.248659,0.005505,0.037918,0.323582,2
2,2,37229,aefe21c3-f761-4a7f-b332-cccef585f556,Mapillary,300351374915837,Singapore,Singapore,1702341327,1.30,103.8000,...,0.0,0.0,3101724.0,1.837808,0.098427,0.391328,0.025908,0.085638,0.248062,3
3,3,37237,2b21fe5c-7dff-47ee-a9d7-de29e60c6db0,Mapillary,240760857851346,Singapore,Singapore,1702341327,1.30,103.8000,...,0.0,0.0,1991090.0,1.568897,0.111652,0.270545,0.000000,0.009440,0.368394,2
4,4,37273,0360bbde-e995-41bd-9bf0-cd23b7bf5543,Mapillary,150295603732550,Singapore,Singapore,1702341327,1.30,103.8000,...,0.0,137690.0,1995155.0,2.077059,0.082021,0.297318,0.000524,0.087229,0.241753,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27298,27298,37144,dc6eee81-9513-4edb-813b-05b83b5127be,Mapillary,2905139663075259,Santiago,Santiago,1152554349,-33.45,-70.6667,...,20850.0,0.0,2013700.0,1.733101,0.084856,0.109167,0.000000,0.045091,0.452324,1
27299,27299,37148,58f7ab3a-95f2-4e63-aa52-9111798c12c9,Mapillary,1188476305232671,Santiago,Santiago,1152554349,-33.45,-70.6667,...,46230.0,189570.0,2244579.0,2.128048,0.291580,0.122134,0.081733,0.089744,0.175526,0
27300,27300,37153,6c330b03-2960-4456-9683-33c2414a2f40,Mapillary,317767673096061,Santiago,Santiago,1152554349,-33.45,-70.6667,...,0.0,31035.0,1968085.0,2.309947,0.107196,0.149529,0.013254,0.154942,0.218123,2
27301,27301,37156,1f3e335f-9029-49f2-8e4a-6b5f522f5bbf,Mapillary,486233076032026,Santiago,Santiago,1152554349,-33.45,-70.6667,...,0.0,128150.0,2001520.0,1.505885,0.001237,0.142749,0.000452,0.384116,0.043040,3
27302,27302,37184,7d061d75-db4a-4c90-8298-61905fa6122d,Mapillary,241753227747318,Santiago,Santiago,1152554349,-33.45,-70.6667,...,0.0,26425.0,2029535.0,1.954534,0.272316,0.082743,0.022912,0.222965,0.226889,3

In [3]:
df_metadata_downloaded = pd.read_csv("data/svi/sampled/metadata_points.csv")
df_metadata_downloaded

,Unnamed: 0,source,orig_id,city,country,continent,uuid
0,0,KartaView,417129806,Singapore,Singapore,Asia,f33495f8-e8bb-4f74-a543-d14504683ab8
1,1,KartaView,371289977,Singapore,Singapore,Asia,dc740ea9-332a-477b-bacd-abf80442b2ef
2,2,Mapillary,452695599162813,Singapore,Singapore,Asia,2168e189-4d7f-4eb7-8ebc-a6ba7db25295
3,3,KartaView,393602974,Singapore,Singapore,Asia,b30a45b9-76d1-4ecf-8550-12fa44bb0384
4,4,Mapillary,434163451597926,Singapore,Singapore,Asia,647e90bd-34e5-49f1-b7be-8a9335c07438
...,...,...,...,...,...,...,...
395,395,Mapillary,2965058333723679,Santiago,Chile,South America,c153326c-0173-491d-8344-f66713096c46
396,396,Mapillary,170224471686444,Santiago,Chile,South America,c0d79220-27ab-4195-880d-364738096d0f
397,397,Mapillary,241753227747318,Santiago,Chile,South America,7d061d75-db4a-4c90-8298-61905fa6122d
398,398,Mapillary,1484499388637530,Santiago,Chile,South America,c1f135fd-9117-45a9-a768-13f7a1137aa8
399,399,Mapillary,1600694800124860,Santiago,Chile,South America,64b6b25b-ca89-4234-8def-37e91184b19c

# Cities

In [4]:
city_names = {
    1702341327: "Singapore",
    1528355309: "Amsterdam",
    1840021543: "San Francisco",
    1566342270: "Abuja",
    1152554349: "Santiago",
}

# San Francisco

## First pass

In [5]:
REMOVED_SVIS_1 = [
    # first pass
    "6f720121-1823-47ba-8a33-59fd1c961eb2",
    "21d1c248-1fa9-48e0-806d-dd8b22007308",
    "56c7707b-f193-4d4f-b53d-9e5e7a13547f",
    "4579bd93-1154-4bb8-bf21-46a6d2dd4074",
    "8559ca86-834d-4e71-b94e-ac24e0066c2d",
    "120934af-6b5a-42c0-8c99-8cace83b2549",
    "bace7a4d-c851-43b4-b70f-b9cbff0f264e",
    "c09c8a47-4685-4ed4-bb10-c18a1fe3de38",
    "caa33225-9ab8-4e17-88f0-a2cfe02a2ff7",
    "cb56740f-cf50-4446-a01d-5041d2b34b8c",
    "db490f56-e6ff-4613-987d-e3606a3178a1",
    "dd95493c-7baf-4de1-8041-3f86ff3dc0ff",
    "de1287f3-cd65-48d4-8dd0-00593a38b147",
    "e3bb9ea6-8cc5-4b15-9b04-cac217806d09",
    "f25da91a-e4e5-4a7d-a965-c5f96813f9e1",
]

In [ ]:
# find out which cluster the removed imgs below to
df_removed = df_clustered[df_clustered["uuid_x"].isin(REMOVED_SVIS_1)]
df_removed.groupby("cluster_label").size()

In [ ]:
df_city = df_clustered[df_clustered["city_id"] == 1840021543]  # San Francisco

# count the number of rows in each cluster that were removed
cluster_counts = df_removed["cluster_label"].value_counts()

# keep track of the samples
df_sampled_city = pd.DataFrame()

# sample the missing amount from each cluster
for cluster_label, count in cluster_counts.items():
    print(f"Sampling {count} samples from cluster {cluster_label}")

    # the available samples are the rows within this cluster that have not been already downloaded (metadata_downloaded)
    available_samples = df_city[
        (df_city["cluster_label"] == cluster_label)
        & (~df_city["uuid_x"].isin(df_metadata_downloaded["uuid"]))
    ]

    sampled_from_cluster = available_samples.sample(n=count, replace=False)

    df_sampled_city = pd.concat([df_sampled_city, sampled_from_cluster])

df_sampled_city

In [ ]:
df_sampled_city["uuid"] = df_sampled_city["uuid_x"]
df_sampled_city.to_csv("download_imgs/filtered_points_sanfrancisco.csv")

## Second pass

In [6]:
REMOVED_SVIS_2 = [  # second pass
   "7f763a86-56bd-4403-8e84-bf24676f50cf",
    "8dd02890-033c-4e62-8735-e2176756a5a8",
]

In [ ]:
df_v2_metadata = df_sampled_city[
    ["source", "orig_id", "city", "country", "continent", "uuid"]
]

df_metadata_all = pd.concat([df_metadata_downloaded, df_v2_metadata])

In [ ]:
# find out which cluster the removed imgs below to
df_removed = df_clustered[df_clustered["uuid_x"].isin(REMOVED_SVIS_2)]
df_removed.groupby("cluster_label").size()

In [ ]:
# count the number of rows in each cluster that were removed
cluster_counts = df_removed["cluster_label"].value_counts()

# keep track of the samples
df_sampled_city = pd.DataFrame()

# sample the missing amount from each cluster
for cluster_label, count in cluster_counts.items():
    print(f"Sampling {count} samples from cluster {cluster_label}")

    # the available samples are the rows within this cluster that have not been already downloaded (metadata_downloaded)
    available_samples = df_city[
        (df_city["cluster_label"] == cluster_label)
        & (~df_city["uuid_x"].isin(df_metadata_all["uuid"]))
    ]

    sampled_from_cluster = available_samples.sample(n=count, replace=False)

    df_sampled_city = pd.concat([df_sampled_city, sampled_from_cluster])

df_sampled_city

In [ ]:
df_sampled_city["uuid"] = df_sampled_city["uuid_x"]
df_sampled_city.to_csv("download_imgs/filtered_points_sanfrancisco_v2.csv")

## Third pass

In [7]:
REMOVED_SVIS_3 = [
    "d075df4b-541c-4b9d-afbc-448f98f9662d",
    "5352831a-9380-4d92-b3bc-4269684062da"
]

In [ ]:
df_v3_metadata = df_sampled_city[
    ["source", "orig_id", "city", "country", "continent", "uuid"]
]

df_metadata_all = pd.concat([df_metadata_all, df_v3_metadata])
df_metadata_all

In [ ]:
# find out which cluster the removed imgs below to
df_removed = df_clustered[df_clustered["uuid_x"].isin(REMOVED_SVIS_3)]
df_removed.groupby("cluster_label").size()

In [ ]:
# count the number of rows in each cluster that were removed
cluster_counts = df_removed["cluster_label"].value_counts()

# keep track of the samples
df_sampled_city = pd.DataFrame()

# sample the missing amount from each cluster
for cluster_label, count in cluster_counts.items():
    print(f"Sampling {count} samples from cluster {cluster_label}")

    # the available samples are the rows within this cluster that have not been already downloaded (metadata_downloaded)
    available_samples = df_city[
        (df_city["cluster_label"] == cluster_label)
        & (~df_city["uuid_x"].isin(df_metadata_all["uuid"]))
    ]

    sampled_from_cluster = available_samples.sample(n=count, replace=False)

    df_sampled_city = pd.concat([df_sampled_city, sampled_from_cluster])

df_sampled_city

In [ ]:
df_sampled_city["uuid"] = df_sampled_city["uuid_x"]
df_sampled_city.to_csv("download_imgs/filtered_points_sanfrancisco_v3.csv")

# Last QC

In [8]:
# final selected pool of samples
df_clustered = pd.read_csv("download_imgs/clustered_points.csv")
df_clustered.shape

/var/folders/kw/9lnn_1r159n28p1krywmf8_w0000gq/T/ipykernel_64200/852928394.py:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_clustered = pd.read_csv("download_imgs/clustered_points.csv")

(27303, 100)

In [9]:
# final selected images 100 images
def get_file_names_without_extension(folder_path):
    file_names = []
    for file_name in os.listdir(folder_path):
        if os.path.isfile(os.path.join(folder_path, file_name)):
            name, _ = os.path.splitext(file_name)
            file_names.append(name)
    return file_names

# Example usage
folder_path = "data/svi/sampled/Final_100/San Francisco"
final_100 = get_file_names_without_extension(folder_path)

folder_path = "data/svi/sampled/Final_80/San Francisco"
final_80 = get_file_names_without_extension(folder_path)

In [10]:
# add lists
to_remove = final_100 + final_80 + REMOVED_SVIS_1 + REMOVED_SVIS_2 + REMOVED_SVIS_3

In [11]:
# filter only this city
df_city = df_clustered[df_clustered["city_id"] == 1840021543]  # San Francisco

In [12]:
# remove already sampled images as well as the ones to remove
df_removed = df_city[~df_city["uuid_x"].isin(to_remove)]
df_removed.shape

(22561, 100)

In [13]:
sampled_from_cluster = df_removed.sample(n=200, replace=False)
sampled_from_cluster.shape

(200, 100)

In [14]:
sampled_from_cluster["uuid"] = sampled_from_cluster["uuid_x"]
sampled_from_cluster.to_csv("download_imgs/filtered_points_sanfrancisco_final.csv")